spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1911?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  application:
    name: tb-provider

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka